version: '3.8'

services:
  # ==========================================
  # INFRASTRUCTURE
  # ==========================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: yelp-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - yelp-network

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: yelp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - yelp-network

  mongodb:
    image: mongo:6.0
    container_name: yelp-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - yelp-network

  mysql:
    image: mysql:8.0
    container_name: yelp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yelp_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - yelp-network

  # ==========================================
  # MICROSERVICES
  # ==========================================
  user-service:
    build:
      context: ./services
      dockerfile: user_service/Dockerfile
    container_name: yelp-user-service
    restart: on-failure
    ports:
      - "8011:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MYSQL_URL=mysql+pymysql://root:rootpassword@mysql:3306/yelp_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - JWT_SECRET=lab2_secret_key_change_later
    depends_on:
      - mongodb
      - mysql
      - kafka
    networks:
      - yelp-network

  restaurant-service:
    build:
      context: ./services
      dockerfile: restaurant_service/Dockerfile
    container_name: yelp-restaurant-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MYSQL_URL=mysql+pymysql://root:rootpassword@mysql:3306/yelp_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - mysql
      - kafka
    networks:
      - yelp-network

  review-service:
    build:
      context: ./services
      dockerfile: review_service/Dockerfile
    container_name: yelp-review-service
    ports:
      - "8003:8003"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MYSQL_URL=mysql+pymysql://root:rootpassword@mysql:3306/yelp_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - mysql
      - kafka
    networks:
      - yelp-network

  worker-service:
    build:
      context: ./services
      dockerfile: worker_service/Dockerfile
    container_name: yelp-worker-service
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MYSQL_URL=mysql+pymysql://root:rootpassword@mysql:3306/yelp_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - mongodb
      - mysql
      - kafka
    networks:
      - yelp-network
    
  ai_service:
    build:
      context: ./services
      dockerfile: ai_service/Dockerfile
    container_name: yelp-ai-service
    ports:
      - "8014:8004"
    volumes:
      - ./services/ai_service:/app
      - ./services/shared:/app/shared
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - GROQ_MODEL=llama-3.3-70b-versatile
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=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
    depends_on:
      - mongodb
    networks:
      - yelp-network

networks:
  yelp-network:
    driver: bridge

volumes:
  mongo_data:
  mysql_data: