apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: yelp
type: Opaque
stringData:
  JWT_SECRET: lab2_secret_key_change_later
  TAVILY_API_KEY: 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
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: yelp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: omkarrajale/yelp-user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef:
                name: yelp-common-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: yelp
spec:
  type: LoadBalancer
  selector:
    app: user-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
  namespace: yelp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: omkarrajale/yelp-restaurant-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: yelp-common-config
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: yelp
spec:
  type: LoadBalancer
  selector:
    app: restaurant-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: yelp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: omkarrajale/yelp-review-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: yelp-common-config
---
apiVersion: v1
kind: Service
metadata:
  name: review-service
  namespace: yelp
spec:
  type: LoadBalancer
  selector:
    app: review-service
  ports:
    - name: http
      port: 8003
      targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service
  namespace: yelp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service
  template:
    metadata:
      labels:
        app: worker-service
    spec:
      containers:
        - name: worker-service
          image: omkarrajale/yelp-worker-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: yelp-common-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-service
  namespace: yelp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-service
          image: omkarrajale/yelp-ai-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: OLLAMA_BASE_URL
              value: http://host.docker.internal:11434
            - name: OLLAMA_MODEL
              value: llama3.2:3b
            - name: TAVILY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: TAVILY_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: yelp
spec:
  type: LoadBalancer
  selector:
    app: ai-service
  ports:
    - name: http
      port: 8004
      targetPort: 8004